---
name: CI

"on":
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - name: Check Nix development environment
        run: nix flake check ./.nix

      - name: Run tests
        run: nix develop ./.nix -c ./gradlew test
